name: Scrape Leetcode

on:
  push: # push to any branch
  workflow_dispatch: # manual
  schedule: # every 30 minutes
    - cron: "0,30 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Fetch latest data
        run: node scraper.js > profile.json

      - name: Commit and push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "fix: update latest data at ${timestamp}" || exit 0
          git push
